### ISSUE TITLE
Formulár

### ISSUE THREAD

**Issue by arinori393** [arinori393/SIvPaVS#2]
Treba vymyslieť aký formulár spravíme a podľa neho potom spraviť xml schému a appku. Ak máte nejaké nápady, sem s nimi.

**Comment by martyciz** [comment]
Tak prve co mi napadne je typicky blocek z obchodu, tam sa daju pekne pridavat line_items. http://www.harmonyservis.sk/files/uploaded/Vzorov%C3%BD%20pokladni%C4%8Dn%C3%BD%20blok.png

alebo napriklad priepustka, ale to neviem ci bude stacit, nie su tam opakujuce sa veci: http://esslm.sk/sites/default/files/esslm-priepustka.pdf

alebo ziadost o zamestnanie: http://www.zones.sk/studentske-prace/slohove-prace/7516-ziadost-o-prijatie-do-zamestnania-vzor/

alebo ziadost o rozvod :D http://www.rozvod-rozchod.sk/vzor-ziadost-o-rozvod-navrh-zeny/d-1016/p1=1076

Martin nepamatas si ake boli podmienky na formular? Viem ze mali mat atribut a asi nejake opakujuce sa veci, len neviem ci to znamena ze musi byt napriklad viac blockov, alebo ze ten jeden blocek co pridavam musi mat viac opakujucich poloziek...

**Comment by arinori393** [comment]
Poziadavky na xmlko boli:
- min. 3 rozne datove typy (tu ale neviem ci sa pocitaju aj zlozene datove typy, t.j. nieco ako triedy, zlozene z niekolkych jednoduchych typov)
- nejake atributy
- opakujuce sa sekcie (pod tymto treba rozumiet viac rovnakych poloziek v jednom formulari, tzn. ze v scheme nastavis, ze nejaka vec sa moze vyskytovat v xml 0 az "n" krat, hranice sa daju zmenit samozrejme) 

Ta priepustka asi nevyhovuje podmienke tych opakovacich sekcii, ale zvysok vyzera fajn. Ten pokladnicny blocik vyzera dobre ale neviem, vytvarat formular na blocik, mozem napisat mail cviciacemu, co na to povie ked tak alebo mozme este nieco ine pohladat.

**Comment by arinori393** [comment]
Ako som tak hladal na nete, napadlo ma, ze nejaky formular na zivotopis by sa tiez dal spravit. Co vy na to ?

**Comment by martyciz** [comment]
a na ten blocek si sa teda pytal?

http://www.profesia.sk/napisat-zivotopis/ taketo nieco chces spravit? :D asi by sme to museli zjednodusit, zivotopis ma dost na vyplnanie

**Comment by arinori393** [comment]
Na ten blocik som sa este nepytal, ale co sa tyka toho zivotopisu, samozrejme by sme si to mohli nejako prisposobit, aby to bolo jednoduchsie. Teraz ma ale tak napadlo, ze by bolo fajn najst nejaky formular alebo skor nejaky dokument, ktory by sa realne mal aj podpisovat. Zivotopis je pravda, ze asi nebude potrebne podpisovat, blocik sa podpisuje ked sa vracia tovar, no neviem. Mozno by bolo fajn este nieco ine pohladat.
